name: bio729p311
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - adwaita-icon-theme=48.0
  - anyio=4.9.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - audioread=3.0.1
  - ax-platform=1.0.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - botorch=0.14.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - catboost=1.2.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.11.13
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - faiss=1.9.0
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.2
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gensim=4.3.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gpytorch=1.14
  - graphite2=1.3.13
  - graphviz=13.0.0
  - gtk3=3.24.43
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.2.1
  - hdbscan=0.8.39
  - hdf5=1.14.3
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jaxtyping=0.3.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libass=0.17.3
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.6
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libfaiss=1.9.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgd=2.3.3
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.84.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopenvino=2025.0.0
  - libopenvino-arm-cpu-plugin=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - librosa=0.10.2.post1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libusb=1.0.29
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxgboost=3.0.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - linear_operator=0.6
  - llvm-openmp=20.1.6
  - llvmlite=0.42.0
  - mako=1.3.10
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - narwhals=1.42.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - notebook-shim=0.2.4
  - numba=0.59.1
  - numpy=1.26.4
  - openblas=0.3.29
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - optree=0.17.0
  - optuna=4.3.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - plotly=6.1.2
  - pooch=1.8.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - py-xgboost=3.0.2
  - pyaml=25.5.0
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pygments=2.19.1
  - pynndescent=0.5.13
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pyre-extensions=0.0.32
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - pysoundfile=0.13.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.7.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - scikit-learn=1.7.0
  - scikit-optimize=0.10.2
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.16
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shap=0.48.0
  - six=1.17.0
  - sleef=3.8
  - slicer=0.0.8
  - smart_open=7.1.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - soxr=0.1.3
  - soxr-python=0.5.0.post1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2022.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wadler-lindig=0.1.7
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x264=1!164.3095
  - x265=3.5
  - xgboost=3.0.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - pip:
      - absl-py==2.3.0
      - accelerate==1.8.0
      - aiocache==0.12.3
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.14.0
      - annotated-types==0.7.0
      - anthropic==0.61.0
      - appdirs==1.4.4
      - apscheduler==3.10.4
      - argon2-cffi==23.1.0
      - arviz==0.22.0
      - asgiref==3.8.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - authlib==1.4.1
      - av==15.0.0
      - axial-positional-embedding==0.3.12
      - azure-ai-documentintelligence==1.0.2
      - azure-core==1.35.0
      - azure-identity==1.20.0
      - azure-storage-blob==12.24.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - bidict==0.23.1
      - biopython==1.85
      - biotite==1.4.0
      - biotraj==1.2.2
      - bitarray==3.6.0
      - bitsandbytes==0.42.0
      - black==25.1.0
      - blinker==1.9.0
      - boto3==1.35.53
      - botocore==1.35.99
      - build==1.3.0
      - cachetools==5.5.2
      - chardet==5.2.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.2.1
      - cloudpathlib==0.21.1
      - colbert-ai==0.2.21
      - coloredlogs==15.0.1
      - cons==0.4.7
      - cryptography==45.0.6
      - ctranslate2==4.6.0
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - ddgs==9.0.0
      - deepchem==2.8.1.dev20250609174000
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - docx2txt==0.8
      - durationpy==0.10
      - ecdsa==0.19.1
      - einops==0.8.1
      - elastic-transport==8.17.1
      - elasticsearch==9.0.1
      - emoji==2.14.1
      - entmax==1.3
      - esm==3.2.1
      - et-xmlfile==2.0.0
      - etuples==0.3.10
      - events==0.5
      - fake-useragent==2.1.0
      - fastapi==0.115.7
      - faster-whisper==1.1.1
      - filelock==3.18.0
      - filetype==1.2.0
      - firecrawl-py==1.12.0
      - flask==3.1.1
      - flatbuffers==25.2.10
      - fpdf2==2.8.2
      - frozenlist==1.7.0
      - fs==2.4.16
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - gast==0.6.0
      - gcp-storage-emulator==2024.8.3
      - git-python==1.0.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.178.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.7.1
      - google-genai==1.15.0
      - google-generativeai==0.8.5
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.63.2
      - greenlet==3.1.1
      - grpcio==1.67.1
      - grpcio-status==1.67.1
      - h5netcdf==1.6.3
      - hf-xet==1.1.4
      - html5lib==1.1
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - hyper-connections==0.1.15
      - iniconfig==2.1.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jiter==0.10.0
      - jmespath==1.0.1
      - jsonpatch==1.33
      - keras==2.15.0
      - kubernetes==33.1.0
      - langchain==0.3.26
      - langchain-community==0.3.26
      - langchain-core==0.3.73
      - langchain-text-splitters==0.3.8
      - langdetect==1.0.9
      - langfuse==2.44.0
      - langsmith==0.3.45
      - ldap3==2.9.1
      - libclang==18.1.1
      - local-attention==1.11.1
      - logical-unification==0.4.6
      - loguru==0.7.3
      - lxml==6.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - milvus-lite==2.5.1
      - minikanren==1.0.5
      - ml-dtypes==0.2.0
      - mmh3==5.2.0
      - moto==5.1.9
      - msal==1.33.0
      - msal-extensions==1.3.1
      - msgpack-numpy==0.4.8
      - multidict==6.5.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.16
      - ninja==1.11.1.4
      - nltk==3.9.1
      - oauthlib==3.2.2
      - olefile==0.47
      - onnxruntime==1.20.1
      - open-webui==0.6.18
      - openai==1.99.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opensearch-py==2.8.0
      - opentelemetry-api==1.36.0
      - opentelemetry-exporter-otlp-proto-common==1.36.0
      - opentelemetry-exporter-otlp-proto-grpc==1.36.0
      - opentelemetry-instrumentation==0.57b0
      - opentelemetry-instrumentation-asgi==0.57b0
      - opentelemetry-instrumentation-fastapi==0.57b0
      - opentelemetry-proto==1.36.0
      - opentelemetry-sdk==1.36.0
      - opentelemetry-semantic-conventions==0.57b0
      - opentelemetry-util-http==0.57b0
      - orjson==3.10.18
      - pandas==2.2.3
      - passlib==1.7.4
      - pathspec==0.12.1
      - peewee==3.18.1
      - peewee-migrate==1.12.2
      - peft==0.15.2
      - perceiver-pytorch==0.8.8
      - performer-pytorch==1.1.4
      - pgvector==0.4.0
      - pinecone==6.0.2
      - pinecone-plugin-interface==0.0.7
      - playwright==1.49.1
      - pluggy==1.6.0
      - portalocker==2.10.1
      - posthog==5.4.0
      - primp==0.15.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psycopg2-binary==2.9.9
      - py-partiql-parser==0.6.1
      - pyarrow==20.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.4.1
      - pyclipper==1.3.0.post6
      - pycrdt==0.12.25
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pydub==0.25.1
      - pyee==12.0.0
      - pyjwt==2.10.1
      - pymc==5.24.1
      - pymdown-extensions==10.14.2
      - pymilvus==2.5.0
      - pymongo==4.14.0
      - pymysql==1.1.1
      - pypandoc==1.15
      - pypdf==4.3.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytensor==2.31.7
      - pytest==8.3.5
      - pytest-docker==3.1.2
      - python-dotenv==1.1.0
      - python-engineio==4.12.2
      - python-iso639==2025.2.18
      - python-jose==3.4.0
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - python-pptx==1.0.2
      - python-socketio==5.13.0
      - pytorch-qnn==1
      - pytube==15.0.0
      - pyxlsb==1.0.10
      - qdrant-client==1.14.3
      - rank-bm25==0.2.2
      - rapidfuzz==3.13.0
      - rapidocr-onnxruntime==1.4.4
      - rdkit==2025.3.2
      - redis==6.4.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - responses==0.25.7
      - restrictedpython==8.0
      - rich==13.9.4
      - rouge==1.0.1
      - rsa==4.9.1
      - s3transfer==0.10.4
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - selfies==2.2.0
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - sincnetconv==0.1.0
      - smmap==5.0.2
      - socksio==1.0.0
      - sqlalchemy==2.0.38
      - starlette==0.45.3
      - starlette-compress==1.6.0
      - tenacity==9.1.2
      - tencentcloud-sdk-python==3.0.1336
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.15.0
      - termcolor==3.1.0
      - tiktoken==0.10.0
      - tokenizers==0.21.1
      - toolz==1.0.0
      - torch-geometric==2.6.1
      - torchaudio==2.7.1
      - torchtext==0.18.0
      - torchvision==0.22.1
      - transformers==4.48.1
      - typer==0.16.0
      - typing-inspection==0.4.1
      - tzlocal==5.3.1
      - ujson==5.10.0
      - unstructured==0.16.17
      - unstructured-client==0.42.2
      - uritemplate==4.2.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - validators==0.35.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - wsproto==1.2.0
      - xarray==2025.7.1
      - xarray-einstats==0.9.1
      - xlrd==2.0.1
      - xlsxwriter==3.2.5
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - youtube-transcript-api==1.1.0
      - zstd==1.5.7.2
